---
 - name: localhost
   hosts: local
   become: true
   roles:
     - system
 
 - name: application loading
   hosts: app
   become: true
   roles: 
     - flask

 - name: loadbalancer
   hosts: lb
   become: true
   roles:
     - haproxy





